### ISSUE TITLE
No Broadcasting from a Non Internet Local AP

### ISSUE THREAD

**Issue by doitranch** [garywill/linux-router#7]
lnxrouter hangs at "lnxrouter setup complete" and I cannot see the ssid on any device... I'm not sure what information to include other than I'm using a Raspberry Pi Zero W running Raspbain Lite... Any help is appreciated.

**Comment by garywill** [comment]
Hi.

>  from a Non Internet Local AP

Does it work well when privide Internet?

Have you tried other method to make AP? Like create_ap?

Check if hostapd's process normal (running? zombie?). You can use `lnxrouter --hostapd-debug 1` to show hostapd's debug log. Post the log with your whole command so that people may find the reason.

**Comment by doitranch** [comment]
Ok will do but I'm out of town at the moment.

**Comment by doitranch** [comment]
Thanks for the help hostapd was dead
